version: 3.8

services:
  gazebo:
    env_file: .env
    build:
      context: .
      dockerfile: docker/ros-jazzy-gazebo.Dockerfile
    container_name: gazebo
    network_mode: host
    working_dir: /workspace

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      IGN_GAZEBO_RESOURCE_PATH: /workspace/assets/models:${IGN_GAZEBO_RESOURCE_PATH}

    devices:
      - /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./.cache/fuel/:/root/.gz/fuel:rw
      - ./.cache/rosdep:/root/.ros/rosdep/sources.cache:rw
      - ./:/workspace
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        cd /workspace/ros2_ws &&
        colcon build --symlink-install &&
        source install/setup.bash &&
        ros2 launch firebot_rl run_gz.launch.py
      "
  
  teleop_gym:
    image: astral/uv:debian
    volumes:
      - ./rl_agent:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./.cache/venv:/app/.venv
      - ./.cache/uv:/root/.cache/uv
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - UV_LINK_MODE=copy
      - UV_PYTHON_INSTALL_DIR=/root/.cache/uv/python
    network_mode: host
    working_dir: /app
    command: sh -c "uv sync && uv run teleop_gym.py"

  train:
    image: astral/uv:debian
    # Headless, so no display/X11 needed
    volumes:
      - ./rl_agent:/app
      - ./.cache/uv:/root/.cache/uv
      - ./.cache/venv:/app/.venv
    environment:
      - UV_LINK_MODE=copy
      - UV_PYTHON_INSTALL_DIR=/root/.cache/uv/python
      - PYTHONUNBUFFERED=1
    devices:
      - /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    network_mode: host
    working_dir: /app
    command: sh -c "uv sync && uv run train.py"
