version: 3.8

services:
  gazebo:
    build:
      context: .
      dockerfile: docker/ros-jazzy-gazebo.Dockerfile
    container_name: gazebo
    network_mode: host
    working_dir: /workspace

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      IGN_GAZEBO_RESOURCE_PATH: /workspace/assets/models:${IGN_GAZEBO_RESOURCE_PATH}

    devices:
      - /dev/dri/card1:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./.cache/fuel/:/root/.gz/fuel:rw
      - ./.cache/rosdep:/root/.ros/rosdep/sources.cache:rw
      - ./:/workspace
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        cd /workspace/ros2_ws &&
        rosdep update &&
        rosdep install --from-paths . -y --ignore-src &&
        colcon build --symlink-install &&
        source install/setup.bash &&
        ros2 launch firebot_rl run_gz.launch.py
      "
